apiVersion: v1
kind: Secret
metadata:
  name: slack-mcp-server-secrets
type: Opaque
stringData:
  # Add your slack bot token and slack workspace team id
  SLACK_BOT_TOKEN: "xoxb-7834804921362-899-CuBn6z3eVw9b"
  SLACK_TEAM_ID: "C0931N6SL5C"
