apiVersion: batch/v1
kind: Job
metadata:
  name: postgres-init-job
spec:
  template:
    spec:
      containers:
        - name: init-db
          image: registry.redhat.io/rhel9/postgresql-15
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "Waiting for PostgreSQL...";
              until pg_isready -h postgresql -p 5432; do sleep 2; done;
              echo "Running SQL script...";
              psql -h postgresql -U claimdb -d claimdb -f /opt/app-root/src/postgresql-startup/init.sql
          env:
            - name: PGPASSWORD
              value: "claimdb"
          volumeMounts:
            - name: init-sql
              mountPath: /opt/app-root/src/postgresql-startup
      restartPolicy: OnFailure
      volumes:
        - name: init-sql
          configMap:
            name: postgres-import
