apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-mcp-server
  labels:
    app: pdf-mcp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pdf-mcp-server
  template:
    metadata:
      labels:
        app: pdf-mcp-server
    spec:
      containers:
        - name: pdf-mcp-server
          image: quay.io/rh-aiservices-bu/mcp-servers:pdf
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - npx -y supergateway --stdio "node build/index.js" --port 8010
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: NPM_CONFIG_CACHE
              value: /tmp/.npm
            - name: XDG_CONFIG_HOME
              value: "/tmp/.chromium"
            - name: XDG_CACHE_HOME
              value: "/tmp/.chromium"
            - name: M2P_OUTPUT_DIR
              value: "/mcp_output"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          volumeMounts:
            - name: tmp-chrome-data
              mountPath: /tmp/chrome-user-data
            - name: tmp-crashpad
              mountPath: /tmp/crashpad
            - name: tmp-chromium
              mountPath: /tmp/.chromium
            - name: mcp-output
              mountPath: /mcp_output
        - name: uploader
          image: registry.access.redhat.com/ubi9/ubi-minimal
          command: ["/bin/sh", "-c"]
          args:
            - |
              while true; do
                for file in /mcp_output/*.pdf; do
                  [ -e "$file" ] || continue
                  filename=$(basename "$file")
                  echo "Uploading $filename..."
                  curl -X POST -F path=$filename -F file=@$file http://reports-repo:9000/upload && rm -f "$file"
                done
                sleep 1
              done
          volumeMounts:
            - name: mcp-output
              mountPath: /mcp_output
      volumes:
        - name: tmp-chrome-data
          emptyDir: {}
        - name: tmp-crashpad
          emptyDir: {}
        - name: tmp-chromium
          emptyDir: {}
        - name: mcp-output
          emptyDir:
            sizeLimit: 1Gi